# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy takelslim image to dockerhub'
  task prod: %w[dockerhub:takelslim:prod:login
                rubylint
                image:build
                dockerhub:takelslim:prod:tag
                dockerhub:takelslim:prod:push]
end
