# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy takelslim image to dockerhub'
  task prod: %w[dockerhub:login
                rubylint
                image:build
                dockerhub:project:prod:tag
                dockerhub:project:prod:push]
end
