# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy takelslim image to dockerhub'
  task prod: %w[dockerhub:login
                rubylint
                images:project:update
                images:project:build
                dockerhub:project:tag
                dockerhub:project:push]
end
