# frozen_string_literal: true

require 'rake'

cmd_image_debianbuster = 'docker pull debian:buster-slim && ' \
        'mkdir -p packer/images/docker && ' \
        'cd packer && packer build ' \
        "--var 'base_repo=debian' " \
        "--var 'base_tag=buster-slim' " \
        "--var 'target_user=#{@project['local_user']}' " \
        "--var 'target_repo=#{@project['name']}' " \
        "--var 'target_tag=debian-buster' " \
        'templates/docker/takelslim/debian-buster/packer.json'

namespace :image do
  namespace :docker do
    namespace :takelslim do
      desc 'Build takelslim debian buster image with packer'
      task :'debian-buster' do
        @commands << cmd_image_debianbuster
      end
    end
  end
end
