stages:
  - build

build-job:
  stage: build
  image: debian:stable-slim
  script:
    - whoami
    - pwd
    - ls -la
    - apt-get update
    - apt-get --yes install ruby ruby-dev
    - gem install takeltau
