stages:
  - build

build-job:
  stage: build
  image: debian:stable-slim
  script:
    # Install docker and ruby
    - apt-get update
    - apt-get --yes install curl gpg
    - mkdir -m 0755 -p /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo 'deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable' | tee /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get --yes install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin g++-aarch64-linux-gnu gcc-aarch64-linux-gnu make ruby ruby-dev

    # Install and configure tau
    # Single quotes work around colon+space gitlab yaml problem
    - gem install takeltau
    - 'echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> ~/.takelage.yml'
    - 'echo "docker_repo: takelbuild" >> ~/.takelage.yml'
    - 'echo "docker_tag: latest-arm64" >> ~/.takelage.yml'

    # Pull takelage image
    - tau update

    # Install mutagen
    - MUTAGEN=$(docker inspect --format '{{ index .Config.Labels "mutagen" }}' takelwerk/takelbuild:latest-amd64)
    - wget -O /tmp/mutagen.tar.gz $MUTAGEN_FILE
    - mutagen daemon start

    # Start an instance of takelage
    - tau docker container daemon
