---
# project settings
name: takelage-img-takelslim
version: debian-buster

pipelines:
  - prod

local_user: packer_local

images:
  project:
    target_user: takelwerk
    target_repo: takelslim
    omit_pipeline_name: prod
    layers:
      - site
