---
name: takelage-img-takelslim
version: debian-bookworm

local_user: packer_local

images:
  project:
    base_user: debian
    base_tag: bookworm-slim
    target_user: takelwerk
    target_repo: takelslim
    packer_template_dir: templates/takelslim/docker
    layers:
      - site
