# frozen_string_literal: true

require 'rake'

cmd_dockerhub_registry_login = 'docker login'

cmd_dockerhub_registry_push = 'docker push ' \
    "#{@project['dockerhub_user']}/" \
    "#{@project['dockerhub_repo']}:" \
    "#{@project['dockerhub_tag']} && " \
    'docker push ' \
    "#{@project['dockerhub_user']}/" \
    "#{@project['dockerhub_repo']}:" \
    'latest'

cmd_dockerhub_registry_tag = 'docker tag ' \
    "#{@project['local_user']}/" \
    "#{@project['name']}:" \
    "#{@project['dockerhub_tag']} " \
    "#{@project['dockerhub_user']}/" \
    "#{@project['dockerhub_repo']}:" \
    "#{@project['dockerhub_tag']} && " \
    'docker tag ' \
    "#{@project['local_user']}/" \
    "#{@project['name']}:" \
    "#{@project['dockerhub_tag']} "\
    "#{@project['dockerhub_user']}/" \
    "#{@project['dockerhub_repo']}:" \
    'latest'

namespace :dockerhub do
  namespace :registry do
    desc 'Log in to hub.docker.com'
    task :login do
      @commands << cmd_dockerhub_registry_login
    end

    desc 'Push multipostgres image to hub.docker.com'
    task :push do
      @commands << cmd_dockerhub_registry_push
    end

    desc 'Tag multipostgres image for hub.docker.com'
    task :tag do
      @commands << cmd_dockerhub_registry_tag
    end
  end
end
