# frozen_string_literal: true

require 'rake'

cmd_dockerhub_registry_login = 'docker login'

cmd_dockerhub_registry_push_latest = \
  'docker push ' \
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  'latest'

cmd_dockerhub_registry_push_version = \
  'docker push ' \
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  "#{@project['version']} "

cmd_dockerhub_registry_tag_latest = \
  'docker tag ' \
  "#{@project['local_user']}/" \
  "#{@project['name']}-%<image>s-%<pipeline>s:" \
  "#{@project['dockerhub_tag']} "\
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  'latest'

cmd_dockerhub_registry_tag_version = \
  'docker tag ' \
  "#{@project['local_user']}/" \
  "#{@project['name']}-%<image>s-%<pipeline>s:" \
  "#{@project['dockerhub_tag']} " \
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  "#{@project['version']}"

# rubocop:disable Metrics/BlockLength
namespace :dockerhub do |env|
  @project['images'].each do |project_image|
    image = project_image.first
    namespace image.to_sym do
      @project['pipelines'].each do |pipeline|
        namespace pipeline.to_sym do
          subtasks(env.scope.path) do
            desc 'Log in to hub.docker.com'
            task :login do
              @commands << cmd_dockerhub_registry_login
            end

            desc 'Push image to hub.docker.com'
            task push: [:"dockerhub:#{image}:#{pipeline}:push:version",
                        :"dockerhub:#{image}:#{pipeline}:push:latest"]
            namespace :push do
              desc 'Push latest image to hub.docker.com'
              task :latest do
                @commands << cmd_dockerhub_registry_push_latest
              end

              desc 'Push version image to hub.docker.com'
              task :version do
                @commands << cmd_dockerhub_registry_push_version
              end
            end

            desc 'Tag image for hub.docker.com'
            task tag: [:"dockerhub:#{image}:#{pipeline}:tag:version",
                       :"dockerhub:#{image}:#{pipeline}:tag:latest"]
            namespace :tag do
              desc 'Tag latest image for hub.docker.com'
              task :latest do
                @commands << format(
                  cmd_dockerhub_registry_tag_latest,
                  image: image,
                  pipeline: pipeline
                )
              end
              desc 'Tag version image for hub.docker.com'
              task :version do
                @commands << format(
                  cmd_dockerhub_registry_tag_version,
                  image: image,
                  pipeline: pipeline
                )
              end
            end
          end
        end
      end
    end
  end
end

# rubocop:enable Metrics/BlockLength
