# frozen_string_literal: true

require 'rake'

cmd_image_build = \
  'docker pull debian:bullseye-slim && ' \
  'mkdir -p packer/images/debian/bullseye && ' \
  'cd packer && packer build ' \
  "--var 'target_user=#{@project['local_user']}' " \
  "--var 'target_repo=#{@project['name']}-project-prod' " \
  'templates/takelslim'

namespace :image do
  desc 'Build takelslim debian bullseye image with packer'
  task :build do
    @commands << cmd_image_build
  end
end
